# Generated by Django 3.1 on 2022-06-07 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheEvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold_tickets',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
