name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/gl4-devops-tesnime-sebei:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/gl4-devops-tesnime-sebei:latest

    - name: Log in to Docker Hub
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $username -p $password

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/gl4-devops-tesnime-sebei